module.exports = {
  TOGGLE_BUTTON_STATE: "TOGGLE_BUTTON_STATE",
  TOGGLE_PLAYER_STATE: "TOGGLE_PLAYER_STATE",
  UPDATE_PLAY_FROM: "UPDATE_PLAY_FROM",
  PLAY_PREV: "PLAY_PREV",
  PLAY_NEXT: "PLAY_NEXT"
};
